# Stage 1: Builder
FROM node:22.12-alpine3.20 AS builder

WORKDIR /build

# Copy package.json and lock files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application source code
COPY src/ src/
COPY tsconfig.json tsconfig.json

# Build the Next.js application
RUN npm run build

# Stage 2: Runner
FROM node:22.12-alpine3.20 AS runner

WORKDIR /app

# Copy necessary files from the builder stage
COPY --from=builder /build/package*.json ./
COPY --from=builder /build/node_modules ./node_modules
COPY --from=builder /build/.next .next/


# Install PM2 to manage the application process
RUN npm install -g pm2

# Set the command to start the application
CMD ["pm2-runtime", "start", "npm", "--", "start"]

